### ISSUE TITLE
 Can't use this plugin on es 7.3.2?

### ISSUE THREAD

**Issue by tablenine** [BigDataBoutique/elasticsearch-repository-swift#12]

**Comment by alexleyke** [comment]
You have to rebuild for 7.3.2. The code base should support any 7.x.

**Comment by tablenine** [comment]
> You have to rebuild for 7.3.2. The code base should support any 7.x.

Thanks for the answer @alexleyke

The current source code seems to depend on version 7.5.2 (master branch)

If you build with 7.3.2, the following error is displayed.

```

> Task :compileJava
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/SwiftRepository.java:28: error: cannot find symbol
import org.elasticsearch.common.blobstore.DeleteResult;
                                         ^
  symbol:   class DeleteResult
  location: package org.elasticsearch.common.blobstore
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/SwiftRepository.java:40: error: cannot find symbol
import org.elasticsearch.repositories.RepositoryCleanupResult;
                                     ^
  symbol:   class RepositoryCleanupResult
  location: package org.elasticsearch.repositories
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/SwiftRepository.java:144: error: cannot find symbol
    private final ConcurrentHashMap<String, Future<DeleteResult>> blobDeletionTasks = new ConcurrentHashMap<>();
                                                   ^
  symbol:   class DeleteResult
  location: class SwiftRepository
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/SwiftRepository.java:197: error: cannot find symbol
    public void addDeletion(String blobName, Future<DeleteResult> task) {
                                                    ^
  symbol:   class DeleteResult
  location: class SwiftRepository
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/SwiftRepository.java:289: error: cannot find symbol
    public void cleanup(long repositoryStateId, ActionListener<RepositoryCleanupResult> listener) {
                                                               ^
  symbol:   class RepositoryCleanupResult
  location: class SwiftRepository
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/blobstore/SwiftBlobContainer.java:27: error: cannot find symbol
import org.elasticsearch.common.blobstore.DeleteResult;
                                         ^
  symbol:   class DeleteResult
  location: package org.elasticsearch.common.blobstore
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/blobstore/SwiftBlobContainer.java:152: error: cannot find symbol
    private DeleteResult internalDeleteBlob(String blobName) throws Exception {
            ^
  symbol:   class DeleteResult
  location: class SwiftBlobContainer
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/blobstore/SwiftBlobContainer.java:178: error: cannot find symbol
    public DeleteResult delete() throws IOException {
           ^
  symbol:   class DeleteResult
  location: class SwiftBlobContainer
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/SwiftRepository.java:171: error: constructor BlobStoreRepository in class BlobStoreRepository cannot be applied to given types;
        super(metadata, Swift.COMPRESS_SETTING.get(settings), namedXContentRegistry, threadPool);
        ^
  required: RepositoryMetaData,Settings,boolean,NamedXContentRegistry,ThreadPool
  found:    RepositoryMetaData,Boolean,NamedXContentRegistry,ThreadPool
  reason: actual and formal argument lists differ in length
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/SwiftRepository.java:208: error: cannot find symbol
        for (Map.Entry<String, Future<DeleteResult>> entry: blobDeletionTasks.entrySet()) {
                                      ^
  symbol:   class DeleteResult
  location: class SwiftRepository
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/SwiftRepository.java:288: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/SwiftRepository.java:295: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/SwiftRepository.java:300: error: method finalizeSnapshot in class BlobStoreRepository cannot be applied to given types;
        super.finalizeSnapshot(snapshotId, indices, startTime, failure, totalShards, shardFailures, repositoryStateId,
             ^
  required: SnapshotId,List<IndexId>,long,String,int,List<SnapshotShardFailure>,long,boolean,Map<String,Object>
  found:    SnapshotId,List<IndexId>,long,String,int,List<SnapshotShardFailure>,long,boolean,MetaData,Map<String,Object>,ActionListener<SnapshotInfo>
  reason: actual and formal argument lists differ in length
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/SwiftRepository.java:317: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/SwiftRepository.java:321: error: no suitable method found for snapshotShard(Store,MapperService,SnapshotId,IndexId,IndexCommit,IndexShardSnapshotStatus,ActionListener<Void>)
        super.snapshotShard(store, mapperService, snapshotId, indexId, snapshotIndexCommit, snapshotStatus, listener);
             ^
    method Repository.snapshotShard(IndexShard,SnapshotId,IndexId,IndexCommit,IndexShardSnapshotStatus) is not applicable
      (actual and formal argument lists differ in length)
    method BlobStoreRepository.snapshotShard(Store,MapperService,SnapshotId,IndexId,IndexCommit,IndexShardSnapshotStatus) is not applicable
      (actual and formal argument lists differ in length)
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/blobstore/SwiftBlobContainer.java:66: error: SwiftBlobContainer is not abstract and does not override abstract method blobExists(String) in BlobContainer
public class SwiftBlobContainer extends AbstractBlobContainer {
       ^
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/blobstore/SwiftBlobContainer.java:136: error: cannot find symbol
            Future<DeleteResult> task = executor.submit(() -> internalDeleteBlob(blobName));
                   ^
  symbol:   class DeleteResult
  location: class SwiftBlobContainer
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/blobstore/SwiftBlobContainer.java:160: error: cannot find symbol
                return new DeleteResult(1, contentLength);
                           ^
  symbol:   class DeleteResult
  location: class SwiftBlobContainer
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/blobstore/SwiftBlobContainer.java:177: error: method does not override or implement a method from a supertype
    @Override
    ^
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/blobstore/SwiftBlobContainer.java:193: error: cannot find symbol
            DeleteResult results = DeleteResult.ZERO;
            ^
  symbol:   class DeleteResult
  location: class SwiftBlobContainer
/Users/user/swiftTest/elasticsearch-repository-swift/src/main/java/org/wikimedia/elasticsearch/swift/repositories/blobstore/SwiftBlobContainer.java:193: error: cannot find symbol
            DeleteResult results = DeleteResult.ZERO;
                                   ^
  symbol:   variable DeleteResult
  location: class SwiftBlobContainer
21 errors
 
```

**Comment by alexleyke** [comment]
I stand corrected. Do you have an option of upgrading to Elasticsearch 7.5.2? It has been tested thoroughly.

**Comment by tablenine** [comment]
Thanks for checking.
We should be using version 7.3.2 due to another issue.

Do you have any plans to modify it to support in version 7.3.2?
